spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
  jpa.hibernate.ddl-auto: create